---
name: Math-SymbolicX-Calculator-Interface-Web
version: 0.01
author:
  - 'Steffen Mueller <smueller@cpan.org>'
abstract: An AJAXy web interface to the calculator
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CGI::Ajax: 0
  Getopt::Long: 0
  HTTP::Server::Simple: 0
  Math::Symbolic: 0.501
  Math::SymbolicX::Calculator::Interface: 0.01
  Params::Util: 0
  Parse::RecDescent: 0
  Pod::Usage: 0
build_requires:
  Test::More: 0
recommends:
  Test::Pod: 1.0
  Test::Pod::Coverage: 1.0
provides:
  Math::SymbolicX::Calculator::Interface::Web:
    file: lib/Math/SymbolicX/Calculator/Interface/Web.pm
    version: 0.01
  Math::SymbolicX::Calculator::Interface::Web::Server:
    file: lib/Math/SymbolicX/Calculator/Interface/Web/Server.pm
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
