--- #YAML:1.0
name: Math-Symbolic
version: 0.502
author:
  - Steffen Mueller <modules at steffen-mueller dot net>
abstract: Symbolic calculations
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
