---
name: Math-Symbolic-Custom-Contains
version: 1.00
author:
  - 'Steffen Mueller <smueller@cpan.org>'
abstract: Find subtrees in Math::Symbolic expressions
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Math::Symbolic: 0.129
build_requires:
  Test::More: 0
recommends:
  Test::Pod: 1.0
  Test::Pod::Coverage: 1.0
provides:
  Math::Symbolic::Custom::Contains:
    file: lib/Math/Symbolic/Custom/Contains.pm
    version: 1.00
generated_by: Module::Build version 0.280501
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
